### PR TITLE
Adapt simulate function to return a data matrix instead of a concatenated vector for multiple subjects

### PR DESCRIPTION
**Pull request by jschepers**
- I deleted obsolete code from the `convert` function + added todo to move it to Unfold.jl
- I adapted the `simulate` function such that the data is returned as a matrix instead of a concatenated vector (i.e. the `convert` function is not used anymore)
- I wrote four testsets for the `simulate` function (single vs. multi-subject, single vs. multi-channel)
  - So far, I only tested the type and size of the returned `data` variable. Maybe you have ideas for more tests or we add them later.
  - I hope these tests are a good fit for `test/simulation.jl`. Otherwise, I can of course move them to another file.

### CODE REVIEW

**Review by behinger — APPROVED** [review]
looks good to me! You want to merge?

**Comment by behinger** [comment]
ah wait - Docs are failling, after we fix that?

**Comment by jschepers** [comment]
> > ah wait - Docs are failling, after we fix that? - rerunning docs if something in main changed to fix it

Did you have a look at what's failing in docs or shall I have a look? :)

**Comment by behinger** [comment]
> > > ah wait - Docs are failling, after we fix that? - rerunning docs if something in main changed to fix it
> 
> Did you have a look at what's failing in docs or shall I have a look? :)

still rerunning

**Comment by behinger** [comment]
still failing. can you have a look?

**Pull request merged**
